name: elixir
description: Tool for commenting `dart analyze` results to GitHub PullRequest.
version: 2.0.0
homepage: https://github.com/blendthink/elixir
repository: https://github.com/blendthink/elixir
documentation: https://github.com/blendthink/elixir
issue_tracker: https://github.com/blendthink/elixir/issues

executables:
  elixir:

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.3.1
  http: ^0.13.5
  meta: ^1.8.0
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.2.0
  mockito: ^5.2.0
  test: ^1.21.4
  version_gen: ^1.0.1
