name: elixir
description: Tool for commenting `dart analyze` results to GitHub PullRequest.
version: 2.0.1
homepage: https://github.com/blendthink/elixir
repository: https://github.com/blendthink/elixir
documentation: https://github.com/blendthink/elixir
issue_tracker: https://github.com/blendthink/elixir/issues

executables:
  elixir:

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.4.0
  file: ^6.1.4
  http: ^0.13.5
  meta: ^1.9.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.3
  mockito: ^5.3.2
  test: ^1.23.1
  version_gen: ^1.0.1
