name: add-contributors
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  UPDATE_CONTRIBUTORS_BRANCH: update-contributors

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: delete old branch (If it exists)
        run: git push origin --delete ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
        continue-on-error: true
      - name: create and push new branch
        run: |
          git branch ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
          git push origin ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
      - uses: BobAnkh/add-contributors@v0.2.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ env.UPDATE_CONTRIBUTORS_BRANCH }}
          PULL_REQUEST: 'main'
