name: check-publish

on:
  push:
    branches:
      - 'release/**'

jobs:
  check-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: copy credentials
        run: .github/scripts/copy-credentials.sh
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      - name: check publish
        run: dart pub publish --dry-run
