name: update-version

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'pubspec.yaml'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/dart-lang/setup-dart
      - uses: dart-lang/setup-dart@v1

      # https://github.com/actions/cache
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ${{ github.workspace }}/.packages
            ${{ github.workspace }}/.dart_tool/package_config.json
          key: ${{ runner.os }}-pubspec-${{ hashFiles(format('{0}{1}', github.workspace, '/pubspec.lock')) }}

      - name: check pubspec.yaml
        run: |
          dart pub get
          dart pub run build_runner build --delete-conflicting-outputs

      # https://github.com/peter-evans/create-pull-request
      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update version
          title: Update version
          body: This was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          base: main
          branch: update-version
          branch-suffix: short-commit-hash
